
### 密码登录
#POST http://localhost:8080/oauth/token?grant_type=password&username=marissa&password=koala
POST http://localhost:8080/oauth/token?grant_type=password&username=liulu&password=123456
Authorization: Basic lit lit
Content-Type: application/x-www-form-urlencoded


###
GET http://localhost:8080/dictionary/list
#Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE1NTc2Mzc1MDIsInVzZXJfbmFtZSI6ImxpdWx1IiwiYXV0aG9yaXRpZXMiOlsiVklFV19ST0xFIiwiUkVNT1ZFX1JPTEUiLCJBRERfVVNFUiIsIkFERF9ST0xFIiwiUkVNT1ZFX0RJQ1RJT05BUlkiLCJWSUVXX0FVVEhPUklUWSIsIk1PRElGWV9NRU5VIiwiTU9ESUZZX09SRyIsIk1PRElGWV9ST0xFIiwiVklFV19QQVJBTSIsIkFERF9QQVJBTSIsIk1PRElGWV9ESUNUSU9OQVJZIiwiVklFV19ESUNUSU9OQVJZIiwiQUREX01FTlUiLCJSRU1PVkVfUEFSQU0iLCJWSUVXX09SRyIsIlZJRVdfTUVOVSIsIk1PRElGWV9QQVJBTSIsIlJFTU9WRV9NRU5VIiwiQUREX0RJQ1RJT05BUlkiLCJBRERfT1JHIiwiUkVNT1ZFX1VTRVIiLCJSRU1PVkVfT1JHIiwiVklFV19VU0VSIiwiTU9ESUZZX1VTRVIiXSwianRpIjoiMjBjOGIzYWEtNTczZC00NTkxLWFmZmUtZWQ4Mjc2YmJlMjhlIiwiY2xpZW50X2lkIjoibGl0Iiwic2NvcGUiOlsicmVhZCIsIndyaXRlIl19.LXZWD4dtTW4fouvF2bXMgCME9-O-SZCK-I8mGSCi_VY
#Cookie: access_token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE1NTc2Mzc1MDIsInVzZXJfbmFtZSI6ImxpdWx1IiwiYXV0aG9yaXRpZXMiOlsiVklFV19ST0xFIiwiUkVNT1ZFX1JPTEUiLCJBRERfVVNFUiIsIkFERF9ST0xFIiwiUkVNT1ZFX0RJQ1RJT05BUlkiLCJWSUVXX0FVVEhPUklUWSIsIk1PRElGWV9NRU5VIiwiTU9ESUZZX09SRyIsIk1PRElGWV9ST0xFIiwiVklFV19QQVJBTSIsIkFERF9QQVJBTSIsIk1PRElGWV9ESUNUSU9OQVJZIiwiVklFV19ESUNUSU9OQVJZIiwiQUREX01FTlUiLCJSRU1PVkVfUEFSQU0iLCJWSUVXX09SRyIsIlZJRVdfTUVOVSIsIk1PRElGWV9QQVJBTSIsIlJFTU9WRV9NRU5VIiwiQUREX0RJQ1RJT05BUlkiLCJBRERfT1JHIiwiUkVNT1ZFX1VTRVIiLCJSRU1PVkVfT1JHIiwiVklFV19VU0VSIiwiTU9ESUZZX1VTRVIiXSwianRpIjoiMjBjOGIzYWEtNTczZC00NTkxLWFmZmUtZWQ4Mjc2YmJlMjhlIiwiY2xpZW50X2lkIjoibGl0Iiwic2NvcGUiOlsicmVhZCIsIndyaXRlIl19.LXZWD4dtTW4fouvF2bXMgCME9-O-SZCK-I8mGSCi_VY



###
GET http://localhost:8080/api/dictionary/root/list
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE1NTc2Mzc1MDIsInVzZXJfbmFtZSI6ImxpdWx1IiwiYXV0aG9yaXRpZXMiOlsiVklFV19ST0xFIiwiUkVNT1ZFX1JPTEUiLCJBRERfVVNFUiIsIkFERF9ST0xFIiwiUkVNT1ZFX0RJQ1RJT05BUlkiLCJWSUVXX0FVVEhPUklUWSIsIk1PRElGWV9NRU5VIiwiTU9ESUZZX09SRyIsIk1PRElGWV9ST0xFIiwiVklFV19QQVJBTSIsIkFERF9QQVJBTSIsIk1PRElGWV9ESUNUSU9OQVJZIiwiVklFV19ESUNUSU9OQVJZIiwiQUREX01FTlUiLCJSRU1PVkVfUEFSQU0iLCJWSUVXX09SRyIsIlZJRVdfTUVOVSIsIk1PRElGWV9QQVJBTSIsIlJFTU9WRV9NRU5VIiwiQUREX0RJQ1RJT05BUlkiLCJBRERfT1JHIiwiUkVNT1ZFX1VTRVIiLCJSRU1PVkVfT1JHIiwiVklFV19VU0VSIiwiTU9ESUZZX1VTRVIiXSwianRpIjoiMjBjOGIzYWEtNTczZC00NTkxLWFmZmUtZWQ4Mjc2YmJlMjhlIiwiY2xpZW50X2lkIjoibGl0Iiwic2NvcGUiOlsicmVhZCIsIndyaXRlIl19.LXZWD4dtTW4fouvF2bXMgCME9-O-SZCK-I8mGSCi_VY

###